language: objective-c
rvm:
  - 2.2
  - jruby
  - 2.1.0
osx_image: xcode8.2
xcode_project: Calculator.xcodeproj
xcode_scheme: Calculator
xcode_sdk: iphonesimulator10.2
before_install:
  - export IOS_SIMULATOR_UDID=$(instruments -s devices | grep "$ios_device ($ios_version)" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g')
  - echo "Prelaunching iOS simulator $IOS_SIMULATOR_UDID"
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
install:
  - bundle install
script:
  - fastlane test
after_success:
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
env:
  global:
    secure: UWadbBjfqIYwnL0PfL/1qMagI7N866vLjagpPQunus2Q24khQd1Qy/X9Bky+belXkk7GnrlPUdpjWe1atqtK8Enb+4DXbp+741P2QHsIs3YUH/D6dlJI7O/saHx6xJD1lCmLjoQEzkckILs6YDrPxS5XE/x0mXlOHKahUOND1tfDot1aKtvD+szJAhFrYnqtDaCAdn1X+NOceR8C83S6e6mxtQ3VjECgLKS+4T5mdfnNeFgxM9XG4gWRDZAQ14vG5Z8wkZiQqTB+BBMI3ZSOmj/BYAQWDnCq744bZQd0Yz2abD3O0a7uKOTAwg7FMQ659B9DnYRdyfHG5pFnw+EC5wIGYYtx8hvJQYG73jUFQF1lhA/Ciagqd1h6MrK4P0QoeuDiYs6uEUC6hKwoiAXMBc+KHZHVErXmcj+k1RCiubJWwwBHTLp42lJPS4W4WzzSaOkabj3KGC7FAS5ejRvmpiBHEF0lxnh0uv3iGcMZ0bfI+HQc22vZLrla9xbK6D+F84ZeGv7nSEN3jHVE4kruV4B9X0lG5vVLIOX7FL7v4YiNB8BMjBQUeO8mN414Wop4JtTeUFEvqGQA9KtPOnGsCzzkaBIVQJOmI2F6vx3dIfJbiX23ssrSxIQ1LcYMKM2iSKS0O/8BRyFQ27kq7cxoPXS+tDeTv2W3ff4doUvFREo=
